name: RightRoute CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Build Project
        run: yarn install && yarn build
      

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2

#      - name: Sync to CodeCommit
#        uses: afinkorea/aws-codecommit-sync@v1.0.0
#        with:
#          repository_name: test1
#          aws_region: ap-northeast-2
#          branch: main

      - uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          notify_when: "success,failure,cancelled,warnings,skipped"
          mention_users_when: "success,failure,cancelled,warnings,skipped"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
